New Github Actions

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -5,8 +5,11 @@ name: GitHub Pages deploy
 
 on:
   push:
-    branches: [main]
+    branches: ['main']
   workflow_dispatch:
+
+env:
+  NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
 
 permissions:
   contents: read
@@ -14,7 +17,7 @@ permissions:
   id-token: write
 
 concurrency:
-  group: 'node'
+  group: 'pages'
   cancel-in-progress: true
 
 jobs:
@@ -24,19 +27,66 @@ jobs:
       - name: Checkout 🛎️
         uses: actions/checkout@v3
 
-      - name: Use Node.js 18.x
+      - name: Detect package manager 👻
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::npx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+
+      - name: Setup Node 🍉
         uses: actions/setup-node@v3
         with:
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
           node-version: '18.x'
 
-      - name: Installing my packages
-        run: npm ci
-
-      - name: Build my App
-        run: npm run build && npm run export && touch ./out/.nojekyll
-
-      - name: Deploy 🚀
-        uses: JamesIves/github-pages-deploy-action@4.4.0
+      - name: Setup Pages 🔧
+        id: pages
+        uses: actions/configure-pages@v1
         with:
-          branch: public
-          folder: out
+          static_site_generator: next
+
+      - name: Restore cache 💾
+        uses: actions/cache@v3
+        with:
+          path: |
+            .next/cache
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+
+      - name: Install dependencies 🥑
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+
+      - name: Build with Next.js 🍄
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
+
+      - name: Static HTML export with Next.js 🥯
+        run: ${{ steps.detect-package-manager.outputs.runner }} next export
+
+      - name: Upload artifact ⛱️
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: ./out
+
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages 🚀
+        id: deployment
+        uses: actions/deploy-pages@v1
